### ISSUE TITLE
Option to disable first header

### ISSUE THREAD

**Issue by ptrbrynt** [zhukic/Sectioned-RecyclerView#11]
Currently it looks like `onPlaceSubheaderBetweenItems(position: Int)` is only called when `position > 0`. That means there's no way of hiding the first header.
I'd like to be able to do this to avoid having to write two different adapters for the same data according to whether or not I want a header. Is it possible for there to be a way to not display that first header?

**Comment by zhukic** [comment]
Hi, @ptrbrynt. Unfortunately, there is now way of hiding the first header which will be automatically added if your data set is not empty. TBH I think this feature is out of the library's scope because the main idea of the library is providing the way to split your data into groups based on common attribute your grouped data has and mark your grouped data with the header. Maybe I will add this feature in future.

**Comment by zhukic** [comment]
Actually, there is only way I see to not display first header. You need to hide your viewholder's view when `onBindSubheaderViewHolder(SubheaderViewHolder subheaderViewHolder, int nextItemPosition)` is called and `nextItemPosition = 0`

**Comment by ptrbrynt** [comment]
@zhukic Hmm, that could work. I'll try it - thanks!
