### ISSUE TITLE
How would I add multiple checks?

### ISSUE THREAD

**Issue by Superblazer** [zhukic/Sectioned-RecyclerView#23]
I checked your sample and it works fantastically. I display different months on the header, but I would like to have another check to see if the day is today. That is I would like to have a header for the first item which will have the day = today display a header just for that, and from the next item the usual grouping according to the month...

**Comment by zhukic** [comment]
Hi @Superblazer.
As I understood your issue correctly, you need to in your implementation of the method `onBindSubheaderViewHolder(SubheaderViewHolder holder, int nextItemPosition)` check `nextItemPosition` whether item at this position is today or not. If today - you display header for today, for months - otherwise.
